### ISSUE TITLE
Error when adding show from trakt page with non default quality.

### ISSUE THREAD

**Issue by tester22** [lad1337/SickBeardConnect#1]
When I tried to add an show from trakt.tv and changed default status to wanted I recieved the following message:

Could not add the show: param: 'status' with given value: '&status=wanted' is out of allowed range

**Comment by lad1337** [comment]
should be fixed with https://github.com/lad1337/SickBeardConnect/commit/255f1d6610c74016250ade6ec5e46a89ac3ed4b6
