### ISSUE TITLE
Out of place UI

### ISSUE THREAD

**Issue by dz0ny** [lad1337/SickBeardConnect#10]
Tabs in widget are in new line (history tab is new line). To fix I had to change

```
.ui-tabs .ui-tabs-nav li {
  width: 33.34%; // changing to something like 33.33 
}
```

**Comment by Watso4183** [comment]
I just posted regarding this on the Google Code site. URL for cross reference as well as screenshot:
http://code.google.com/p/sickbeardconnect/issues/detail?id=1

**Comment by lad1337** [comment]
fixed with https://github.com/lad1337/SickBeardConnect/commit/cda64fcc1c56e2d4c0aa0e3cb605917552a34772
and in public version 0.1.20, already in the chrome webstore
