### ISSUE TITLE
Typo on "ComingEP" dropdown

### ISSUE THREAD

**Issue by jbroome** [lad1337/SickBeardConnect#13]
Currently says "No Entry's", should be "No Entries".

![screenshot-2012-08-27-12 00 26 116](https://f.cloud.github.com/assets/955184/682007/762ad95e-d9be-11e2-9332-102dc1537eb9.png)

Thanks!

**Comment by lad1337** [comment]
thanks fixed in https://github.com/lad1337/SickBeardConnect/commit/260d87aba6ad4695a9a81bacfb221d83b033bd86 i will send it out to google as soon as my own sickbeard runs again and i can test it :)
